[tool.black]
line-length = 120
exclude = '''
/(
    \.venv
  | migrations
  | alembic
  | __pycache__
)/
'''

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["src/tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
