"""init schema

Revision ID: 0d61325ef1f8
Revises: 
Create Date: 2025-10-11 10:16:55.792570

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0d61325ef1f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_of_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workcenters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_of_materials_id', sa.Integer(), nullable=False),
    sa.Column('workcenter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_of_materials_id'], ['bill_of_materials.id'], ),
    sa.ForeignKeyConstraint(['workcenter_id'], ['workcenters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parts',
    sa.Column('workcenter_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lead_time', sa.Interval(), nullable=False),
    sa.ForeignKeyConstraint(['workcenter_id'], ['workcenters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_workcenter_id'), 'parts', ['workcenter_id'], unique=False)
    op.create_table('boms_parts',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('bill_of_materials_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_of_materials_id'], ['bill_of_materials.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('part_id', 'bill_of_materials_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boms_parts')
    op.drop_index(op.f('ix_parts_workcenter_id'), table_name='parts')
    op.drop_table('parts')
    op.drop_table('orders')
    op.drop_table('workcenters')
    op.drop_table('bill_of_materials')
    # ### end Alembic commands ###
