"""remove workcenter_id from orders table

Revision ID: b0c7e7e7f399
Revises: 0d61325ef1f8
Create Date: 2025-10-12 11:17:26.359833

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b0c7e7e7f399'
down_revision: Union[str, Sequence[str], None] = '0d61325ef1f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('orders_workcenter_id_fkey'), 'orders', type_='foreignkey')
    op.drop_column('orders', 'workcenter_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('workcenter_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('orders_workcenter_id_fkey'), 'orders', 'workcenters', ['workcenter_id'], ['id'])
    # ### end Alembic commands ###
